### ISSUE TITLE
Animation bug on moving platforms

### ISSUE THREAD

**Issue by gre-v-el** [ThreeCoffees/Unity-Platformer#19]
The walking animation of the player is playing while the player is standing on a moving platform.

Possible fix: instead of checking player velocity when calculating `isWalking`, check `player velocity - current platform velocity`

**Comment by ThreeCoffees** [comment]
Possible solution: set isWalking based on moveInput instead of velocity

**Comment by ThreeCoffees** [comment]
Should be fixed now on branch lab-2.
Works for me at least.
Also fixed isGrounded activating in jump points.
